import { useState } from "react";
import toast from "react-hot-toast";
import api from "../api/axios";

const SubmitSection = ({ jobData, jobId, setJobData }) => {
  const [submitting, setSubmitting] = useState(false);
  const [checkingPodSlip, setCheckingPodSlip] = useState(false);
  const [podSlipUrl, setPodSlipUrl] = useState(null);

  const refetchJob = async () => {
    const response = await api.get(`/api/partner/jobs/${jobId}`);
    setJobData(response.data.jobData);
  };

  const handleSubmit = async () => {
    setSubmitting(true);
    try {
      const response = await api.post(`/api/jobs/pickup/${jobId}/submit`);
      toast.success(response.data.message || "Pod slip generating");
      await refetchJob();

      setTimeout(() => {
        setSubmitting(false);
      }, 4000);
      return;
    } catch (err) {
      toast.error(err?.response?.data?.message || "Failed to submit job");
    }
    setSubmitting(false);
  };

  const handleCheckPodSlip = async () => {
    setCheckingPodSlip(true);
    try {
      const response = await api.get(`/api/jobs/${jobId}/pod-slip`);
      setPodSlipUrl(response.data.podSlip.pdfUrl);
      toast.success("Pod slip is ready");
    } catch (err) {
      if (err?.response?.status === 404) {
        toast.error("Not generated yet — check back shortly");
      } else {
        toast.error(err?.response?.data?.message || "Failed to check pod slip");
      }
    } finally {
      setCheckingPodSlip(false);
    }
  };

  const handleDownloadPodSlip = async () => {
    try {
      const response = await fetch(podSlipUrl);
      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = "pod-slip.pdf";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(blobUrl);
    } catch (err) {
      toast.error("Failed to download pod slip", err);
    }
  };

  return (
    <div className="border-t border-gray-200 pt-4">
      <h3 className="font-semibold text-black mb-2">Submission</h3>
      <p className="text-xs text-gray-500 mb-2">
        Requires weight and price to be saved first.
      </p>
      {jobData.podSlipGenerated && (
        <p className="text-xs text-gray-500 mb-2">
          Last generated by{" "}
          <span className="font-medium text-gray-700">
            {jobData.podGeneratedBy}
          </span>
        </p>
      )}

      <div className="flex flex-wrap items-center gap-3">
        <button
          onClick={handleSubmit}
          disabled={submitting}
          className="text-sm px-4 py-2 rounded-lg bg-black text-white hover:bg-gray-800 transition disabled:opacity-50 cursor-pointer"
        >
          {submitting ? "Generating..." : "Generate pod slip"}
        </button>

        <button
          onClick={handleCheckPodSlip}
          disabled={checkingPodSlip}
          className="text-sm px-4 py-2 rounded-lg bg-gray-200 text-black hover:bg-gray-300 transition disabled:opacity-50 cursor-pointer"
        >
          {checkingPodSlip ? "Checking..." : "Check pod slip"}
        </button>

        {podSlipUrl && (
          <button
            onClick={handleDownloadPodSlip}
            className="text-sm px-4 py-2 rounded-lg bg-gray-200 text-black hover:bg-gray-300 transition cursor-pointer"
          >
            Download pod slip
          </button>
        )}
      </div>
    </div>
  );
};

export default SubmitSection;
